In [1]:
import numpy as np

In [6]:
s = 5
s

5

In [3]:
v = np.array([4,3,1])
v

array([4, 3, 1])

In [4]:
m = np.array([[4,3,5],[7,3,5]])
m

array([[4, 3, 5],
       [7, 3, 5]])

###data types

In [7]:
type(s)

int

In [8]:
type(v)

numpy.ndarray

In [9]:
type(m)

numpy.ndarray

In [10]:
s_array = np.array(5)
s_array

array(5)

In [11]:
type(s_array)

numpy.ndarray

## shape

In [13]:
m.shape

(2, 3)

In [14]:
v.shape

(3,)

In [21]:
v.reshape(3,1)

array([[4],
       [3],
       [1]])

In [23]:
s.shape

AttributeError: 'int' object has no attribute 'shape'

In [24]:
s_array.shape

()

## Creation of a Tensor

In [25]:
m1 = np.array([[4,3,5],[7,3,5]])
m1

array([[4, 3, 5],
       [7, 3, 5]])

In [26]:
m2 = np.array([[2,8,0],[-1,4,6]])
m2

array([[ 2,  8,  0],
       [-1,  4,  6]])

In [27]:
t = np.array([m1,m2])
t

array([[[ 4,  3,  5],
        [ 7,  3,  5]],

       [[ 2,  8,  0],
        [-1,  4,  6]]])

In [28]:
t.shape

(2, 2, 3)

## manually creation of tensors

In [30]:
m_tensor = np.array([[[4,3,6],[3,5,1]],[[9,8,1],[4,7,0]],[[3,4,5],[4,7,4]]])
m_tensor

array([[[4, 3, 6],
        [3, 5, 1]],

       [[9, 8, 1],
        [4, 7, 0]],

       [[3, 4, 5],
        [4, 7, 4]]])

In [31]:
m_tensor.shape

(3, 2, 3)

## Addition of matrices

In [32]:
m1+m2

array([[ 6, 11,  5],
       [ 6,  7, 11]])

In [33]:
m1-m2

array([[ 2, -5,  5],
       [ 8, -1, -1]])