In [1]:
import numpy as np

In [2]:
m1 = np.array([[2,4,5],[3,4,5]])

In [3]:
m1

array([[2, 4, 5],
       [3, 4, 5]])

In [4]:
m1.T

array([[2, 3],
       [4, 4],
       [5, 5]])

## transposing scalers

In [5]:
s1 = np.array([5])

In [6]:
s1

array([5])

In [7]:
s1.T

array([5])